### ISSUE TITLE
Graylog 2.1 

### ISSUE THREAD

**Issue by cerw** [blue-yonder/bonfire#17]
Hello

Does hit package have support for Graylog 2.1 and can it also have option for PATH as Graylog 2.1 allows you to have API on same port eg //graylog.com/api/

thanks

**Comment by mahrz** [comment]
I haven't tested it with Graylog version 2 yet, and the endpoint is fixed as host:port currently. I'll consider adding custom paths and testing it with a newer version.

**Comment by valentin-krasontovitsch** [comment]
so assuming that the only thing we need is support for custom endpoints (which sounds like a somewhat reasonable assumption as i've been running bonfire against a 2.x version of graylog), this is fixed in ec7d5306cb2b6c1c7536d266a3cc15cce5b90726 and just needs to be pushed as a new release (cf. #26)

**Comment by valentin-krasontovitsch** [comment]
pushed in v0.0.8 today.
