### ISSUE TITLE
maintenance of the project

### ISSUE THREAD

**Issue by valentin-krasontovitsch** [blue-yonder/bonfire#28]
@mahrz - Hey Malte, it seems like this project might not be maintained anymore. Any chances of becoming a contributor / taking over the maintenance? Or should we just fork, and do our own thing? Appreciate any feedback.

**Comment by josegonzalez** [comment]
@mahrz I'd be happy to jump in, if only to ensure things get released/triaged as appropriate. Would you mind granting me access to this repo, as well as `savant` access to the pypi package?

**Comment by mahrz** [comment]
@BY-jk can you add @valentin-krasontovitsch and @josegonzalez as contributers with merge permissions? It seems like I cannot change the permissions.

I added `savant` as a maintainer on pypi.org. I'm happy to help if things get traction again and really appreciate your initiative!

**Comment by BY-jk** [comment]
Welcome @valentin-krasontovitsch & @josegonzalez. I added you as Collaborators with write access to the bonfire repo. This should give you read, clone, push rights on the repo. The only thing both of you cannot do is adding more collaborators (that would require admin level on this repo).
@mahrz let me know if this works for all of you. 
Otherwise, happy coding and great to see that you are contributing!

**Comment by valentin-krasontovitsch** [comment]
Thanks : )
